In [138]:
import pandas as pd
import numpy as np

In [139]:
df =pd.read_csv("Bengaluru_House_Data.csv")

In [140]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [141]:
df.shape

(13320, 9)

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [143]:
for column in df.columns:
    print(df[column].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                              541
Sarjapur  Road                          399
Electronic City                         304
Kanakpura Road                          273
Thanisandra                             237
                                       ...
Duddanahalli                              1
Doddanakunte                              1
Jogupalya                                 1
Subhash Nagar                             1
Kengeri Satellite Town KHB Apartment      1
Name: count, Length: 1294, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Prtates    59
Sryalan    59
GMown E    56
           ..
SNadeAr     1
DSellil     1
Shensit     1
VKvenas     1
Vemes H     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64
********************

In [144]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [145]:
df.drop(columns=["area_type","availability","society","balcony"],inplace=True)

In [146]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [148]:
df["location"].value_counts()

location
Whitefield                              541
Sarjapur  Road                          399
Electronic City                         304
Kanakpura Road                          273
Thanisandra                             237
                                       ...
Duddanahalli                              1
Doddanakunte                              1
Jogupalya                                 1
Subhash Nagar                             1
Kengeri Satellite Town KHB Apartment      1
Name: count, Length: 1294, dtype: int64

In [149]:
df["size"].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [150]:
df["size"].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [151]:
df["size"].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [152]:
df["size"]=df["size"].fillna("2 BHK")

In [153]:
df["bath"]=df["bath"].fillna(df["bath"].median())

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [155]:
df['bhk']=df['size'].str.split().str.get(0).astype(int)

In [156]:
df[df.bhk > 20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [157]:
df["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [158]:
def convert_range(x):
    temp=x.split('-')
    if len(temp) == 2:
        return (float(temp[0]) + float(temp[1]))/2
    try:
        return float(x)
    except:
        return None

In [159]:
df["total_sqft"]=df["total_sqft"].apply(convert_range)

In [160]:
df.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

### price per Square Feet

In [161]:
df["price_per_sqft"]=df["price"] + 100000 / df["total_sqft"]

In [162]:
df["price_per_sqft"]

0        133.766970
1        158.461538
2        131.444444
3        160.746220
4        134.333333
            ...
13315    259.960324
13316    427.777778
13317    147.642419
13318    509.326509
13319    198.818182
Name: price_per_sqft, Length: 13320, dtype: float64

In [163]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    13274.000000
mean    1559.626694      2.688814    112.565627      2.802778      202.507241
std     1238.405258      1.338754    148.971674      1.294496      901.183975
min        1.000000      1.000000      8.000000      1.000000       53.666667
25%     1100.000000      2.000000     50.000000      2.000000      138.241748
50%     1276.000000      2.000000     72.000000      3.000000      155.362278
75%     1680.000000      3.000000    120.000000      3.000000      195.113805
max    52272.000000     40.000000   3600.000000     43.000000   100120.000000

In [164]:
df["location"].value_counts()

location
Whitefield                              541
Sarjapur  Road                          399
Electronic City                         304
Kanakpura Road                          273
Thanisandra                             237
                                       ...
Duddanahalli                              1
Doddanakunte                              1
Jogupalya                                 1
Subhash Nagar                             1
Kengeri Satellite Town KHB Apartment      1
Name: count, Length: 1294, dtype: int64

In [165]:
df["location"] = df["location"].str.strip()
location_count = df["location"].value_counts()

In [166]:
location_count

location
Whitefield                              541
Sarjapur  Road                          399
Electronic City                         304
Kanakpura Road                          273
Thanisandra                             237
                                       ...
Duddanahalli                              1
Doddanakunte                              1
Jogupalya                                 1
Subhash Nagar                             1
Kengeri Satellite Town KHB Apartment      1
Name: count, Length: 1294, dtype: int64

In [167]:
location_count_less_10=location_count[location_count<=10]
location_count_less_10

location
Basapura                                10
Dairy Circle                            10
Nagappa Reddy Layout                    10
Naganathapura                           10
Sector 1 HSR Layout                     10
                                        ..
Duddanahalli                             1
Doddanakunte                             1
Jogupalya                                1
Subhash Nagar                            1
Kengeri Satellite Town KHB Apartment     1
Name: count, Length: 1053, dtype: int64

In [168]:
df['location']=df['location'].apply(lambda x:'other' if x in location_count_less_10 else x)

In [169]:
df['location'].value_counts()

location
other                        2885
Whitefield                    541
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

#### outlier detection and removal

In [170]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    13274.000000
mean    1559.626694      2.688814    112.565627      2.802778      202.507241
std     1238.405258      1.338754    148.971674      1.294496      901.183975
min        1.000000      1.000000      8.000000      1.000000       53.666667
25%     1100.000000      2.000000     50.000000      2.000000      138.241748
50%     1276.000000      2.000000     72.000000      3.000000      155.362278
75%     1680.000000      3.000000    120.000000      3.000000      195.113805
max    52272.000000     40.000000   3600.000000     43.000000   100120.000000

In [171]:
(df['total_sqft']/df['bhk']).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [172]:
df=df[((df['total_sqft']/df['bhk']) >=300)]
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838      188.329726
std     1261.271296      1.077938    152.077329      0.976678      140.006628
min      300.000000      1.000000      8.440000      1.000000       53.666667
25%     1116.000000      2.000000     49.000000      2.000000      137.331773
50%     1300.000000      2.000000     70.000000      3.000000      153.124847
75%     1700.000000      3.000000    115.000000      3.000000      185.532448
max    52272.000000     16.000000   3600.000000     16.000000     3613.986014

In [173]:
df.shape

(12530, 7)

In [174]:
df.price_per_sqft.describe()

count    12530.000000
mean       188.329726
std        140.006628
min         53.666667
25%        137.331773
50%        153.124847
75%        185.532448
max       3613.986014
Name: price_per_sqft, dtype: float64

In [175]:
def remove_outliers_sqft(data):
    df_output =pd.DataFrame()
    for key,subdf in data.groupby('location'):
        m=np.mean(subdf.price_per_sqft)
        st=np.std(subdf.price_per_sqft)
        gen_df = subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))]
        df_output = pd.concat([df_output,gen_df],ignore_index =True)
    return df_output
df= remove_outliers_sqft(df)
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10795.000000  10795.000000  10795.000000  10795.000000    10795.000000
mean    1466.766258      2.449097     88.027028      2.560815      166.323270
std     1049.919643      0.905421     67.199597      0.848045       55.642218
min      350.000000      1.000000     10.000000      1.000000       75.000000
25%     1109.000000      2.000000     49.270000      2.000000      136.905349
50%     1270.000000      2.000000     68.000000      2.000000      150.457944
75%     1611.000000      3.000000    100.000000      3.000000      173.646439
max    52272.000000     13.000000    995.000000     13.000000     1014.577134

In [176]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats ={}
        for bhk,bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk]={
                "mean": np.mean(bhk_df.price_per_sqft),
                "std" : np.std(bhk_df.price_per_sqft),
                "count":bhk_df.shape[0]
            }
        
        print(location,bhk_stats)    
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats =bhk_stats.get(bhk-1)
            if stats and stats['count']>5:
                exclude_indices=np.append(exclude_indices,bhk_df[bhk_df.price_per_sqft<=(stats['mean'])].index.values)
    return df.drop(exclude_indices,axis="index")

In [177]:
data =bhk_outlier_remover(df)

1st Block Jayanagar {2: {'mean': np.float64(228.97165991902835), 'std': 0.0, 'count': 1}, 3: {'mean': np.float64(252.33878663940013), 'std': 30.692552505673017, 'count': 3}, 4: {'mean': np.float64(408.81632653061223), 'std': 0.0, 'count': 1}}
1st Phase JP Nagar {1: {'mean': np.float64(169.04761904761904), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(185.4458916553977), 'std': 24.824156757205355, 'count': 7}, 3: {'mean': np.float64(233.09212429790395), 'std': 27.540391531840474, 'count': 7}, 4: {'mean': np.float64(269.2057232828481), 'std': 11.471772319775193, 'count': 3}}
2nd Phase Judicial Layout {2: {'mean': np.float64(135.50805152979066), 'std': 11.740136018395972, 'count': 3}, 3: {'mean': np.float64(125.5165360247875), 'std': 7.445082348699404, 'count': 6}}
2nd Stage Nagarbhavi {4: {'mean': np.float64(298.81481481481484), 'std': 18.580858035148943, 'count': 5}, 5: {'mean': np.float64(265.0), 'std': 0.0, 'count': 1}}
5th Block Hbr Layout {2: {'mean': np.float64(141.01578091312345), 'std': 2.97248950577549, 'count': 3}, 3: {'mean': np.float64(148.74015748031496), 'std': 0.0, 'count': 1}, 5: {'mean': np.float64(157.77777777777777), 'std': 0.0, 'count': 1}}
5th Phase JP Nagar {2: {'mean': np.float64(147.12658590270348), 'std': 10.194570674211212, 'count': 19}, 3: {'mean': np.float64(146.12268129458428), 'std': 9.89168537676227, 'count': 9}, 5: {'mean': np.float64(150.0), 'std': 0.0, 'count': 1}, 7: {'mean': np.float64(135.0), 'std': 0.0, 'count': 1}}
6th Phase JP Nagar {2: {'mean': np.float64(160.22395610552596), 'std': 17.781748968665124, 'count': 9}, 3: {'mean': np.float64(182.6818310002758), 'std': 16.610834270722112, 'count': 3}}
7th Phase JP Nagar {1: {'mean': np.float64(170.16666666666669), 'std': 10.166666666666671, 'count': 2}, 2: {'mean': np.float64(152.87194996512446), 'std': 15.910297183263667, 'count': 61}, 3: {'mean': np.float64(164.96857415162367), 'std': 24.342939776260298, 'count': 65}, 4: {'mean': np.float64(204.1275439169966), 'std': 23.824513613966275, 'count': 2}, 7: {'mean': np.float64(190.83333333333334), 'std': 0.0, 'count': 1}}
8th Phase JP Nagar {2: {'mean': np.float64(139.34032381432706), 'std': 13.548788135442429, 'count': 22}, 3: {'mean': np.float64(136.24704197664215), 'std': 17.46968437210406, 'count': 17}, 4: {'mean': np.float64(163.36273911273912), 'std': 19.833895502743207, 'count': 4}, 5: {'mean': np.float64(132.80346820809248), 'std': 0.0, 'count': 1}}
9th Phase JP Nagar {1: {'mean': np.float64(186.66666666666666), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(146.66522897356737), 'std': 11.381123293680329, 'count': 20}, 3: {'mean': np.float64(137.4970258491673), 'std': 11.008865150583627, 'count': 9}, 4: {'mean': np.float64(132.6315789473684), 'std': 0.0, 'count': 1}}
AECS Layout {2: {'mean': np.float64(145.0261522504946), 'std': 7.189421686865309, 'count': 7}, 3: {'mean': np.float64(140.0), 'std': 0.0, 'count': 1}}
Abbigere {1: {'mean': np.float64(158.3893681323574), 'std': 2.3295861160086133, 'count': 2}, 2: {'mean': np.float64(144.8355683723057), 'std': 7.939846050996708, 'count': 13}, 3: {'mean': np.float64(124.36507936507937), 'std': 0.0, 'count': 1}}
Akshaya Nagar {2: {'mean': np.float64(140.58155543195085), 'std': 7.435096478480158, 'count': 19}, 3: {'mean': np.float64(149.31247763043737), 'std': 8.053359446910417, 'count': 30}}
Ambalipura {1: {'mean': np.float64(173.69012987012985), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(151.0300261447596), 'std': 9.890758011489725, 'count': 13}, 3: {'mean': np.float64(178.48929137011737), 'std': 19.00155182176633, 'count': 8}, 4: {'mean': np.float64(183.2896613190731), 'std': 4.926024955436716, 'count': 2}}
Ambedkar Nagar {2: {'mean': np.float64(161.95001742655305), 'std': 2.642296607595931, 'count': 5}, 3: {'mean': np.float64(187.14237408260266), 'std': 34.57092544249922, 'count': 20}, 4: {'mean': np.float64(311.9539538007657), 'std': 21.47551692102432, 'count': 3}}
Amruthahalli {1: {'mean': np.float64(223.67611683848799), 'std': 2.009450171821314, 'count': 2}, 2: {'mean': np.float64(146.39771263533024), 'std': 10.633208280437936, 'count': 12}, 3: {'mean': np.float64(159.0716231318179), 'std': 28.67320642016476, 'count': 7}}
Anandapura {2: {'mean': np.float64(137.36888738220574), 'std': 10.2740814443611, 'count': 14}, 3: {'mean': np.float64(134.6770661811746), 'std': 12.435814825242126, 'count': 4}, 4: {'mean': np.float64(147.17552887364207), 'std': 0.0, 'count': 1}}
Ananth Nagar {2: {'mean': np.float64(134.83043940838533), 'std': 9.454138358456822, 'count': 20}, 3: {'mean': np.float64(129.39185186331292), 'std': 13.503590791385395, 'count': 3}, 4: {'mean': np.float64(170.33333333333331), 'std': 0.0, 'count': 1}}
Anekal {1: {'mean': np.float64(183.16666666666666), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(144.1019135504156), 'std': 26.39673741128382, 'count': 22}, 3: {'mean': np.float64(148.46367008053045), 'std': 17.843573831236487, 'count': 7}, 4: {'mean': np.float64(119.33333333333333), 'std': 0.0, 'count': 1}}
Anjanapura {2: {'mean': np.float64(138.51674784731296), 'std': 12.78873846599818, 'count': 7}, 3: {'mean': np.float64(150.86367546874058), 'std': 27.117375103508184, 'count': 3}, 4: {'mean': np.float64(140.05405405405406), 'std': 0.0, 'count': 1}}
Ardendale {2: {'mean': np.float64(143.36671865715982), 'std': 7.115484132768584, 'count': 4}, 3: {'mean': np.float64(150.99270642986966), 'std': 6.094413600747796, 'count': 10}, 4: {'mean': np.float64(202.85883378129432), 'std': 21.020425672600485, 'count': 7}}
Arekere {2: {'mean': np.float64(150.39442531910976), 'std': 7.212674525978517, 'count': 5}, 3: {'mean': np.float64(165.75916731691757), 'std': 16.18526676924824, 'count': 3}, 4: {'mean': np.float64(178.90036900369003), 'std': 0.0, 'count': 1}}
Attibele {1: {'mean': np.float64(218.37308447681536), 'std': 30.81259782488878, 'count': 9}, 2: {'mean': np.float64(164.30817068009867), 'std': 15.838047976614149, 'count': 6}, 3: {'mean': np.float64(174.8456790123457), 'std': 15.84439966556255, 'count': 6}, 4: {'mean': np.float64(141.12546125461256), 'std': 0.0, 'count': 1}}
BEML Layout {2: {'mean': np.float64(148.4554487359266), 'std': 1.7744055407541095, 'count': 5}, 3: {'mean': np.float64(135.0), 'std': 0.0, 'count': 4}, 5: {'mean': np.float64(266.6666666666667), 'std': 0.0, 'count': 1}}
BTM 2nd Stage {2: {'mean': np.float64(160.49843481118984), 'std': 37.98843105926932, 'count': 16}, 3: {'mean': np.float64(207.8446532359576), 'std': 55.879413511629366, 'count': 6}}
BTM Layout {1: {'mean': np.float64(242.22222222222223), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(148.34241230423456), 'std': 6.745426552888759, 'count': 4}, 3: {'mean': np.float64(152.17775455918914), 'std': 13.44760504767044, 'count': 7}, 6: {'mean': np.float64(195.3030303030303), 'std': 0.0, 'count': 1}}
Babusapalaya {2: {'mean': np.float64(132.49530864543388), 'std': 6.361389691327711, 'count': 12}, 3: {'mean': np.float64(128.75825748151155), 'std': 5.983518326630431, 'count': 7}}
Badavala Nagar {2: {'mean': np.float64(163.99293563579278), 'std': 4.5, 'count': 4}, 3: {'mean': np.float64(165.9440684095152), 'std': 3.862182425213869, 'count': 7}}
Balagere {1: {'mean': np.float64(173.8284526619849), 'std': 7.396311552105108, 'count': 3}, 2: {'mean': np.float64(161.00646041030842), 'std': 6.7337199351275485, 'count': 29}}
Banashankari {1: {'mean': np.float64(220.27777777777777), 'std': 21.388888888888886, 'count': 2}, 2: {'mean': np.float64(146.8318919860176), 'std': 15.8872772310217, 'count': 31}, 3: {'mean': np.float64(161.81254033443366), 'std': 32.65854361271473, 'count': 30}, 4: {'mean': np.float64(135.0), 'std': 0.0, 'count': 1}}
Banashankari Stage II {2: {'mean': np.float64(193.89334649522462), 'std': 14.776099022831994, 'count': 4}, 3: {'mean': np.float64(246.0079365079365), 'std': 69.01550840647836, 'count': 4}, 4: {'mean': np.float64(233.33333333333331), 'std': 0.0, 'count': 1}, 5: {'mean': np.float64(460.7142857142857), 'std': 0.0, 'count': 1}}
Banashankari Stage III {2: {'mean': np.float64(158.5297532411378), 'std': 20.668828695703358, 'count': 3}, 3: {'mean': np.float64(147.46586665777437), 'std': 15.474392809579484, 'count': 10}, 4: {'mean': np.float64(167.12791783380018), 'std': 19.634357201441123, 'count': 3}, 6: {'mean': np.float64(183.33333333333334), 'std': 0.0, 'count': 1}}
Banashankari Stage V {2: {'mean': np.float64(141.2920048309179), 'std': 8.903647342995171, 'count': 2}, 3: {'mean': np.float64(120.80210496842126), 'std': 9.046224465615182, 'count': 9}}
Banashankari Stage VI {2: {'mean': np.float64(144.7611164282733), 'std': 0.41070893784586643, 'count': 3}, 3: {'mean': np.float64(141.52833147291702), 'std': 0.3364707186060199, 'count': 3}, 4: {'mean': np.float64(215.83333333333334), 'std': 5.0, 'count': 2}}
Banaswadi {1: {'mean': np.float64(224.75332068311195), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(147.04956523209998), 'std': 6.703784810253956, 'count': 10}, 3: {'mean': np.float64(137.0), 'std': 0.0, 'count': 1}, 5: {'mean': np.float64(238.49652595317338), 'std': 45.947918491271096, 'count': 2}}
Banjara Layout {2: {'mean': np.float64(156.68571428571428), 'std': 3.352380952380969, 'count': 2}, 3: {'mean': np.float64(185.05555555555554), 'std': 5.055555555555557, 'count': 2}, 4: {'mean': np.float64(180.0), 'std': 8.333333333333329, 'count': 2}}
Bannerghatta {2: {'mean': np.float64(163.43690695655957), 'std': 9.910511822476089, 'count': 4}, 3: {'mean': np.float64(198.4666913749192), 'std': 25.971173799050835, 'count': 4}}
Bannerghatta Road {1: {'mean': np.float64(197.51435107376284), 'std': 14.32225857970453, 'count': 5}, 2: {'mean': np.float64(147.53189292345533), 'std': 12.05176026387082, 'count': 59}, 3: {'mean': np.float64(150.08936994204473), 'std': 19.939606082781037, 'count': 70}, 4: {'mean': np.float64(189.2328365951043), 'std': 32.31363720263354, 'count': 7}, 5: {'mean': np.float64(195.03703703703704), 'std': 0.0, 'count': 1}, 6: {'mean': np.float64(204.05405405405406), 'std': 0.0, 'count': 1}}
Basavangudi {1: {'mean': np.float64(231.7101990049751), 'std': 32.45646766169152, 'count': 2}, 2: {'mean': np.float64(200.80899047000742), 'std': 8.474244700404924, 'count': 6}, 3: {'mean': np.float64(210.0370461719932), 'std': 18.157498395010407, 'count': 12}, 4: {'mean': np.float64(240.3832042397065), 'std': 50.38320423970649, 'count': 2}}
Basaveshwara Nagar {2: {'mean': np.float64(177.30158730158726), 'std': 36.1439759744849, 'count': 7}, 3: {'mean': np.float64(224.86140507658783), 'std': 34.31394722623209, 'count': 3}, 5: {'mean': np.float64(351.6666666666667), 'std': 0.0, 'count': 1}}
Battarahalli {2: {'mean': np.float64(136.46946122560692), 'std': 10.320969127982135, 'count': 9}, 3: {'mean': np.float64(147.51170195341214), 'std': 7.082822084886015, 'count': 8}}
Begur {2: {'mean': np.float64(141.6278722882106), 'std': 16.599357153623917, 'count': 4}, 3: {'mean': np.float64(133.10833188115322), 'std': 8.295047296801375, 'count': 8}, 4: {'mean': np.float64(125.09615384615384), 'std': 0.0, 'count': 1}}
Begur Road {2: {'mean': np.float64(127.5027765606513), 'std': 5.636118501882088, 'count': 39}, 3: {'mean': np.float64(125.66265219222888), 'std': 8.484174883712457, 'count': 28}}
Bellandur {1: {'mean': np.float64(145.26315789473682), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(147.76853434040524), 'std': 11.785851474932189, 'count': 52}, 3: {'mean': np.float64(160.25813512578577), 'std': 23.699825625670154, 'count': 33}, 4: {'mean': np.float64(158.3827160493827), 'std': 0.0, 'count': 1}}
Benson Town {2: {'mean': np.float64(251.35721098675225), 'std': 67.94315789410494, 'count': 5}, 3: {'mean': np.float64(330.58702038541753), 'std': 109.20476201558503, 'count': 5}, 4: {'mean': np.float64(577.5254610514726), 'std': 0.0, 'count': 1}}
Bharathi Nagar {2: {'mean': np.float64(139.08518236020723), 'std': 6.353303134374601, 'count': 8}}
Bhoganhalli {2: {'mean': np.float64(153.02706966249158), 'std': 14.153375686892065, 'count': 15}, 3: {'mean': np.float64(167.92317486895124), 'std': 16.59638019646857, 'count': 14}, 4: {'mean': np.float64(161.53619941109386), 'std': 10.050592567909723, 'count': 9}}
Billekahalli {2: {'mean': np.float64(159.2169264317229), 'std': 15.690957122874538, 'count': 9}, 3: {'mean': np.float64(166.17467114617153), 'std': 21.112561938933965, 'count': 5}}
Binny Pete {1: {'mean': np.float64(204.15304568238776), 'std': 6.283175269062518, 'count': 4}, 2: {'mean': np.float64(195.26007326007326), 'std': 0.0, 'count': 1}, 3: {'mean': np.float64(231.73981665994177), 'std': 24.889283118679955, 'count': 8}, 4: {'mean': np.float64(237.2530316474416), 'std': 2.2394262052647207, 'count': 2}}
Bisuvanahalli {2: {'mean': np.float64(147.72877497481568), 'std': 3.969109141585991, 'count': 8}, 3: {'mean': np.float64(136.32865152289324), 'std': 5.121840577254264, 'count': 30}}
Bommanahalli {2: {'mean': np.float64(140.925973037107), 'std': 11.005597574066103, 'count': 16}, 3: {'mean': np.float64(139.5128766232933), 'std': 14.253095736507671, 'count': 10}, 4: {'mean': np.float64(132.61904761904762), 'std': 0.0, 'count': 1}}
Bommasandra {2: {'mean': np.float64(139.07537596157175), 'std': 4.916493310942347, 'count': 19}, 3: {'mean': np.float64(131.23805952795684), 'std': 7.3068572070516735, 'count': 10}}
Bommasandra Industrial Area {2: {'mean': np.float64(123.86432302291678), 'std': 3.2799206370071454, 'count': 12}, 3: {'mean': np.float64(123.7918998979163), 'std': 5.540923859157351, 'count': 5}}
Bommenahalli {3: {'mean': np.float64(221.8170836850082), 'std': 43.029477236434666, 'count': 3}, 4: {'mean': np.float64(199.17138607731872), 'std': 6.898840255647202, 'count': 6}}
Brookefield {2: {'mean': np.float64(152.93950553813565), 'std': 12.341803199422232, 'count': 20}, 3: {'mean': np.float64(160.92474045046018), 'std': 25.395526234448198, 'count': 14}, 4: {'mean': np.float64(199.50996674696174), 'std': 19.756880806769455, 'count': 7}, 5: {'mean': np.float64(226.28205128205127), 'std': 0.0, 'count': 1}}
Budigere {1: {'mean': np.float64(162.89005235602093), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(145.36018645198124), 'std': 3.9516289789266166, 'count': 24}, 3: {'mean': np.float64(145.66634362181674), 'std': 5.107636554659591, 'count': 22}}
CV Raman Nagar {2: {'mean': np.float64(149.99536231868737), 'std': 12.52799188310637, 'count': 21}, 3: {'mean': np.float64(148.78101387091087), 'std': 16.083336478864876, 'count': 6}}
Chamrajpet {1: {'mean': np.float64(283.01980198019805), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(218.598155674868), 'std': 30.434358221812467, 'count': 5}, 3: {'mean': np.float64(175.4034781179423), 'std': 10.202659563016258, 'count': 3}, 4: {'mean': np.float64(246.9290152024243), 'std': 24.29743625505587, 'count': 2}}
Chandapura {1: {'mean': np.float64(171.5805429432755), 'std': 0.3044106134101097, 'count': 12}, 2: {'mean': np.float64(136.70281870024724), 'std': 14.195377254756016, 'count': 42}, 3: {'mean': np.float64(122.96227684150224), 'std': 9.525643278953472, 'count': 21}, 4: {'mean': np.float64(153.22781220454144), 'std': 24.513859281536398, 'count': 3}}
Channasandra {2: {'mean': np.float64(133.2715130600787), 'std': 9.50069386722774, 'count': 24}, 3: {'mean': np.float64(135.04431351116585), 'std': 14.472510899907103, 'count': 9}, 4: {'mean': np.float64(156.11666666666667), 'std': 0.0, 'count': 1}}
Chikka Tirupathi {3: {'mean': np.float64(163.2418229406972), 'std': 3.749362055533085, 'count': 4}, 4: {'mean': np.float64(159.29299588090365), 'std': 8.106855769714546, 'count': 6}}
Chikkabanavar {2: {'mean': np.float64(138.49193508607507), 'std': 6.771222808661747, 'count': 2}, 3: {'mean': np.float64(132.12878787878788), 'std': 10.371212121212125, 'count': 2}, 4: {'mean': np.float64(146.15853658536588), 'std': 25.50813008130082, 'count': 2}, 5: {'mean': np.float64(126.83333333333333), 'std': 11.833333333333329, 'count': 2}, 8: {'mean': np.float64(135.0), 'std': 0.0, 'count': 1}}
Chikkalasandra {2: {'mean': np.float64(139.86744594498273), 'std': 9.778316735408653, 'count': 13}, 3: {'mean': np.float64(131.33974413586645), 'std': 6.668282499454778, 'count': 14}}
Choodasandra {2: {'mean': np.float64(144.83752099712024), 'std': 10.430761661295714, 'count': 12}, 3: {'mean': np.float64(143.05934482934745), 'std': 8.778260372912301, 'count': 10}}
Cooke Town {1: {'mean': np.float64(211.99115044247787), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(258.4795321637427), 'std': 0.0, 'count': 1}, 3: {'mean': np.float64(311.4792019426844), 'std': 26.431748242870146, 'count': 4}}
Cox Town {1: {'mean': np.float64(194.28925619834712), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(196.09401152720116), 'std': 34.86960889422158, 'count': 6}, 3: {'mean': np.float64(192.88561005163953), 'std': 19.435146078480706, 'count': 4}}
Cunningham Road {3: {'mean': np.float64(710.9936284300763), 'std': 131.6276764053927, 'count': 8}, 4: {'mean': np.float64(1014.5771339075959), 'std': 0.0, 'count': 1}, 5: {'mean': np.float64(970.1880341880342), 'std': 0.0, 'count': 1}}
Dasanapura {1: {'mean': np.float64(169.56293785310734), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(162.61063441880225), 'std': 9.997007783599006, 'count': 7}, 3: {'mean': np.float64(145.76049766718506), 'std': 0.0, 'count': 1}}
Dasarahalli {2: {'mean': np.float64(143.57953119645933), 'std': 10.668171119260517, 'count': 9}, 3: {'mean': np.float64(160.0041379971057), 'std': 13.68386497665386, 'count': 3}}
Devanahalli {1: {'mean': np.float64(169.41862965766146), 'std': 14.010907154813285, 'count': 8}, 2: {'mean': np.float64(145.19303307753398), 'std': 20.37205839371716, 'count': 15}, 3: {'mean': np.float64(154.85151842318245), 'std': 33.74098149947703, 'count': 14}, 4: {'mean': np.float64(227.40965732087227), 'std': 4.257009345794387, 'count': 2}, 5: {'mean': np.float64(141.66666666666666), 'std': 0.0, 'count': 1}}
Devarachikkanahalli {2: {'mean': np.float64(137.89012769757028), 'std': 13.3004236768199, 'count': 9}, 3: {'mean': np.float64(133.84432492117512), 'std': 7.4413850511682496, 'count': 5}}
Dodda Nekkundi {2: {'mean': np.float64(137.13701361173332), 'std': 6.896007749487131, 'count': 19}, 3: {'mean': np.float64(163.28674020158837), 'std': 21.358809927398458, 'count': 7}}
Doddaballapur {1: {'mean': np.float64(201.9051987767584), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(166.75), 'std': 0.0, 'count': 1}, 3: {'mean': np.float64(235.22444265969565), 'std': 44.469020182023996, 'count': 3}, 4: {'mean': np.float64(271.4290912871699), 'std': 29.76242462050324, 'count': 2}}
Doddakallasandra {2: {'mean': np.float64(138.42112802325008), 'std': 1.6176832036531472, 'count': 6}, 3: {'mean': np.float64(127.47435320270863), 'std': 0.46100544178310154, 'count': 4}}
Doddathoguru {1: {'mean': np.float64(158.83333333333334), 'std': 0.0, 'count': 1}, 2: {'mean': np.float64(141.42176772769994), 'std': 8.437802838918865, 'count': 17}, 3: {'mean': np.float64(132.09586213100124), 'std': 6.137160349690291, 'count': 5}}
Domlur {1: {'mean': np.float64(211.10042735042734), 'std': 10.468439169365498, 'count': 3}, 2: {'mean': np.float64(203.4458906648053), 'std': 56.28516757606799, 'count': 4}, 3: {'mean': np.float64(220.61114927820674), 'std': 54.1135208523294, 'count': 14}}
Dommasandra {2: {'mean': np.float64(136.8695804785539), 'std': 5.809495813119866, 'count': 6}, 3: {'mean': np.float64(128.52248015692615), 'std': 5.142617462169331, 'count': 3}}
EPIP Zone {2: {'mean': np.float64(162.09566235813952), 'std': 4.968424083599632, 'count': 6}, 3: {'mean': np.float64(195.19206174054654), 'std': 18.27176806893856, 'count': 9}, 4: {'mean': np.float64(196.31578947368422), 'std': 0.0, 'count': 1}}
Electronic City {1: {'mean': np.float64(177.3338125657338), 'std': 19.34821056198635, 'count': 10}, 2: {'mean': np.float64(142.2179342220755), 'std': 15.11278195523346, 'count': 182}, 3: {'mean': np.float64(139.42060723852492), 'std': 18.35971473990377, 'count': 78}, 4: {'mean': np.float64(167.72487582054586), 'std': 10.663273378282101, 'count': 5}}

In [178]:
df.shape

(10795, 7)

In [179]:
 df

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,3 BHK,1630.0,3.0,194.00,3,255.349693
1,1st Block Jayanagar,3 BHK,1875.0,2.0,235.00,3,288.333333
2,1st Block Jayanagar,3 BHK,1200.0,2.0,130.00,3,213.333333
3,1st Block Jayanagar,2 BHK,1235.0,2.0,148.00,2,228.971660
4,1st Block Jayanagar,4 BHK,2450.0,4.0,368.00,4,408.816327
...,...,...,...,...,...,...,...
10790,other,1 Bedroom,812.0,1.0,26.00,1,149.152709
10791,other,3 BHK,1440.0,2.0,63.93,3,133.374444
10792,other,2 BHK,1075.0,2.0,48.00,2,141.023256
10793,other,4 Bedroom,1200.0,5.0,325.00,4,408.333333
10794,other,4 BHK,3600.0,5.0,400.00,4,427.777778

In [180]:
df.drop(columns=["size","price_per_sqft"],inplace=True)

## cleaned data

In [181]:
df.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      1630.0   3.0  194.0    3
1  1st Block Jayanagar      1875.0   2.0  235.0    3
2  1st Block Jayanagar      1200.0   2.0  130.0    3
3  1st Block Jayanagar      1235.0   2.0  148.0    2
4  1st Block Jayanagar      2450.0   4.0  368.0    4

In [182]:
x=df.drop(columns=["price"])
y=df["price"]

In [183]:
df.columns

Index(['location', 'total_sqft', 'bath', 'price', 'bhk'], dtype='object')

In [184]:
from sklearn.model_selection import train_test_split

In [185]:
### train test split

In [186]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [187]:
x_train.shape

(8636, 4)

In [188]:
y_train.shape

(8636,)

In [189]:
x_test.shape

(2159, 4)

In [190]:
y_train.shape

(8636,)

In [191]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [192]:
numerical_features = ["total_sqft","bath","bhk"]
categorical_features=["location"]

In [193]:
preprocessor=ColumnTransformer(
    transformers=[
        ("num","passthrough",numerical_features),
        ("cat",OneHotEncoder(handle_unknown="ignore"),categorical_features)
    ]
)

In [194]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

In [195]:
linear_pipeline =Pipeline([
    ("preprocessor",preprocessor),
    ("model",LinearRegression())
])

In [196]:
linear_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['total_sqft', 'bath',
                                                   'bhk']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location'])])),
                ('model', LinearRegression())])

In [197]:
y_pred=linear_pipeline.predict(x_test)
print(y_pred[:10])

[ 94.12666806 101.96745372  80.48196363  68.63270719  51.2907107
  95.77026902  84.4705792   94.5846902  185.80059086  61.75182184]

In [198]:
linear_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['total_sqft', 'bath',
                                                   'bhk']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location'])])),
                ('model', LinearRegression())])

In [199]:
from sklearn.metrics import r2_score ,mean_absolute_error,mean_squared_error

In [200]:
y_pred_linear=linear_pipeline.predict(x_test)

In [201]:
###  Evaluation Metrics

In [202]:
r2=r2_score(y_test,y_pred_linear)
mae=mean_absolute_error(y_test,y_pred_linear)
rmse=np.sqrt(mean_squared_error(y_test,y_pred_linear))

In [203]:
r2

0.5639498879151215

In [204]:
mae

25.28244454153174

In [205]:
rmse

np.float64(43.38933884235147)

In [206]:
from sklearn.model_selection import cross_val_score

In [207]:
cv_scores=cross_val_score(
    linear_pipeline,
    x_train,
    y_train,
    cv=5,
    scoring="r2"
)

In [208]:
cv_scores

array([0.4914667 , 0.63916643, 0.64477504, 0.59262399, 0.58430263])

In [209]:
cv_scores.mean()

np.float64(0.5904669572016351)

In [210]:
from sklearn.tree import DecisionTreeRegressor

In [211]:
dt_pipeline=Pipeline([
    ("preprocessor",preprocessor),
    ("model",DecisionTreeRegressor(random_state=42))
])

In [212]:
## train
dt_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['total_sqft', 'bath',
                                                   'bhk']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location'])])),
                ('model', DecisionTreeRegressor(random_state=42))])

In [213]:
## predict 
y_pred_dt=dt_pipeline.predict(x_test)

In [214]:
## Evaluate
r2_dt=r2_score(y_test,y_pred_dt)
mae_dt=mean_absolute_error(y_test,y_pred_dt)
rmse_dt=np.sqrt(mean_squared_error(y_test,y_pred_dt))

In [215]:
r2_dt

0.6485086257371654

In [216]:
mae_dt

20.47716069927398

In [217]:
rmse_dt

np.float64(38.95580355536084)

In [218]:
cv_dt=cross_val_score(
    dt_pipeline,
    x_train,
    y_train,
    cv=5,
    scoring="r2"
)

In [219]:
cv_dt

array([0.60670123, 0.60632857, 0.60783796, 0.64569002, 0.62255206])

In [220]:
cv_dt.mean()

np.float64(0.6178219686847287)

In [221]:
### Random forest Regressor

In [222]:
from sklearn.ensemble import RandomForestRegressor

In [223]:
rf_pipeline=Pipeline([
    ("preprocessor",preprocessor),
    ("model",RandomForestRegressor(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    ))
])

In [224]:
rf_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['total_sqft', 'bath',
                                                   'bhk']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location'])])),
                ('model', RandomForestRegressor(n_jobs=-1, random_state=42))])

In [225]:
## predict 
y_pred_rf=rf_pipeline.predict(x_test)

In [226]:
## Evaluate 
r2_rf=r2_score(y_test,y_pred_rf)
mae_rf=mean_absolute_error(y_test,y_pred_rf)
rmse_rf=np.sqrt(mean_squared_error(y_test,y_pred_rf))

In [227]:
r2_rf

0.7564995391553426

In [228]:
mae_rf

17.637441962747104

In [229]:
rmse_rf

np.float64(32.423860706922014)

In [230]:
cv_rf=cross_val_score(
    rf_pipeline,
    x_train,
    y_train,cv=5,
    scoring="r2"
)

In [231]:
cv_rf

array([0.69735848, 0.72098514, 0.72648848, 0.73702207, 0.72670222])

In [232]:
cv_rf.mean()

np.float64(0.7217112783015522)

In [233]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "R2": [
        r2,
        r2_dt,
        r2_rf
    ],
    "MAE": [
        mae,
        mae_dt,
        mae_rf
    ],
    "RMSE": [
        rmse,
        rmse_dt,
        rmse_rf
    ]
})

print(results)

               Model        R2        MAE       RMSE
0  Linear Regression  0.563950  25.282445  43.389339
1      Decision Tree  0.648509  20.477161  38.955804
2      Random Forest  0.756500  17.637442  32.423861

In [234]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

In [235]:
param_distributions = {
    "model__n_estimators": randint(100, 500),
    "model__max_depth": [None, 10, 20, 30, 40, 50],
    "model__min_samples_split": randint(2, 10),
    "model__min_samples_leaf": randint(1, 5),
    "model__max_features": ["sqrt", "log2", None]
}

In [236]:
rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(...))
])

In [237]:
random_search = RandomizedSearchCV(
    estimator=rf_pipeline,
    param_distributions=param_distributions,
    n_iter=30,
    cv=5,
    scoring="r2",
    random_state=42,
    n_jobs=-1,
    verbose=1
)

random_search.fit(x_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num',
                                                                               'passthrough',
                                                                               ['total_sqft',
                                                                                'bath',
                                                                                'bhk']),
                                                                              ('cat',
                                                                               OneHotEncoder(handle_unknown='ignore'),
                                                                               ['location'])])),
                                             ('model',
                                              RandomForestRegressor(n_estimators=Ellipsis))]),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'model__max_depth': [None, 10, 20, 30,
                                                             40, 50],...
                                        'model__min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001D9EF04B950>,
                                        'model__min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001D9EF085150>,
                                        'model__n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001D9EF086470>},
                   random_state=42, scoring='r2', verbose=1)

In [238]:
random_search.best_params_

{'model__max_depth': None,
 'model__max_features': 'log2',
 'model__min_samples_leaf': 1,
 'model__min_samples_split': 9,
 'model__n_estimators': 161}

In [239]:
random_search.best_score_

np.float64(0.7534202552521735)

In [240]:
from sklearn.model_selection import GridSearchCV

In [241]:
best_params = random_search.best_params_

param_grid = {
    "model__n_estimators": [
        max(100, best_params["model__n_estimators"] - 50),
        best_params["model__n_estimators"],
        best_params["model__n_estimators"] + 50
    ],
    
    "model__max_depth": [
        best_params["model__max_depth"]
    ],
    
    "model__min_samples_split": [
        max(2, best_params["model__min_samples_split"] - 1),
        best_params["model__min_samples_split"],
        best_params["model__min_samples_split"] + 1
    ],
    
    "model__min_samples_leaf": [
        max(1, best_params["model__min_samples_leaf"] - 1),
        best_params["model__min_samples_leaf"],
        best_params["model__min_samples_leaf"] + 1
    ],
    
    "model__max_features": [
        best_params["model__max_features"]
    ]
}

In [244]:
grid_search = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="r2",
    n_jobs=-1,
    verbose=1
)

grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         'passthrough',
                                                                         ['total_sqft',
                                                                          'bath',
                                                                          'bhk']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['location'])])),
                                       ('model',
                                        RandomForestRegressor(n_estimators=Ellipsis))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [None],
                         'model__max_features': ['log2'],
                         'model__min_samples_leaf': [1, 1, 2],
                         'model__min_samples_split': [8, 9, 10],
                         'model__n_estimators': [111, 161, 211]},
             scoring='r2', verbose=1)

In [ ]:
print("Final Best Parameters:")
print(grid_search.best_params_)

print("\nBest Cross-Validation R²:")
print(grid_search.best_score_)

In [ ]:
import pickle

In [ ]:
import pickle

# Save the complete pipeline
with open("house_price_model.pkl", "wb") as file:
    pickle.dump(best_rf_model, file)

print("Model saved successfully!")